version: '3.4'

services:
  customerserviceclean.api:
    container_name: customerserviceclean.api
    image: ${DOCKER_REGISTRY-}customerservicecleanapi
    build:
      context: .
      dockerfile: CustomerServiceClean.API/Dockerfile
  gateway:
    container_name: gateway
    image: ${DOCKER_REGISTRY-}gateway
    build:
      context: .
      dockerfile: Gateway/Dockerfile
