version: '3.4'

services:
  customerserviceclean.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoSettings:ConnectionString=mongodb://root:155202Asd...@mongodb:27017
      - HttpClientProperty:DeleteOrderUrl=https://gateway/order/customer
    ports:
      - "8000:80"
  documentservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8001:80"
  gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5005:80"
  userservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8002:80"
